/**
 * ACE (IBM Equal Access) rule metadata: toolkit level and axe-style tags per policy.
 * Generated by scripts/generate-ace-rule-metadata.mjs into src/generated/ace-rule-metadata.json.
 */

import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export type AceToolkitLevel =
  | 'LEVEL_ONE'
  | 'LEVEL_TWO'
  | 'LEVEL_THREE'
  | 'LEVEL_FOUR'

export interface AceRuleMetaEntry {
  readonly toolkitLevel: AceToolkitLevel
  readonly tags: readonly string[]
}

export type AcePolicyId =
  | 'WCAG_2_0'
  | 'WCAG_2_1'
  | 'WCAG_2_2'
  | 'IBM_Accessibility'

export interface AceRuleMetadataFile {
  readonly engineVersion: string
  readonly generatedRef: string
  readonly byPolicy: Record<
    AcePolicyId,
    Record<string, AceRuleMetaEntry>
  >
}

let cached: AceRuleMetadataFile | null = null

function metadataPath(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  return join(here, '..', 'generated', 'ace-rule-metadata.json')
}

/** Load metadata (cached). Safe to call from tools after build copies JSON to dist/generated. */
export function loadAceRuleMetadata(): AceRuleMetadataFile {
  if (!cached) {
    const raw = readFileSync(metadataPath(), 'utf8')
    cached = JSON.parse(raw) as AceRuleMetadataFile
  }
  return cached
}

/** Reset cache (tests). */
export function __resetAceRuleMetadataCache(): void {
  cached = null
}

const ALL_POLICIES: readonly AcePolicyId[] = [
  'WCAG_2_2',
  'WCAG_2_1',
  'WCAG_2_0',
  'IBM_Accessibility',
]

/**
 * Resolve metadata for a rule under the ACE policies used for this scan, then any known policy.
 */
export function getAceRuleMeta(
  ruleId: string,
  activePolicies: readonly string[]
): AceRuleMetaEntry | undefined {
  const data = loadAceRuleMetadata()
  const tried = new Set<string>()
  for (const p of activePolicies) {
    if (p !== 'WCAG_2_2' && p !== 'WCAG_2_1' && p !== 'WCAG_2_0' && p !== 'IBM_Accessibility') {
      continue
    }
    tried.add(p)
    const row = data.byPolicy[p as AcePolicyId]?.[ruleId]
    if (row) return row
  }
  for (const p of ALL_POLICIES) {
    if (tried.has(p)) continue
    const row = data.byPolicy[p]?.[ruleId]
    if (row) return row
  }
  return undefined
}
